# Services
services:
  # Apache + PHP
  apache_php_examen:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    container_name: proyectoExamenphp
    # Preparamos un volumen para almacenar nuestro código
    volumes:
      - ./src/:/var/www/html
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini-development
    expose:
      - 80
    ports:
      - 8090:80
    networks:
      - examen
    links:
      - mariadbexamen
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mariadbexamen:
    image: mariadb
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: examenbd
      MARIADB_USER: miguel
      MARIADB_PASSWORD: leugim
    volumes:
      - ./.docker/mariadb:/var/lib/mysql:Z
    ports:
      - 3320:3306
    networks:
      - examen


networks:
  examen:
    name: examen
    driver: bridge

